### ISSUE TITLE
[BUG] Ax graves not loading at start up but loads with plugman

### ISSUE THREAD

**Issue by PixelsTurtle** [Artillex-Studios/Issues#19]
### Description of the bug

[02:59:37] [Server thread/INFO]: [AxGraves] Enabling AxGraves v1.14.3
[02:59:38] [Server thread/ERROR]: Error occurred while enabling AxGraves v1.14.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.base/java.lang.String.replace(String.java:3086) ~[?:?]
	at AxGraves-1.14.3.jar/com.artillexstudios.axgraves.grave.Grave.<init>(Grave.java:79) ~[AxGraves-1.14.3.jar:?]
	at AxGraves-1.14.3.jar/com.artillexstudios.axgraves.grave.SpawnedGraves.loadFromFile(SpawnedGraves.java:94) ~[AxGraves-1.14.3.jar:?]
	at AxGraves-1.14.3.jar/com.artillexstudios.axgraves.AxGraves.enable(AxGraves.java:56) ~[AxGraves-1.14.3.jar:?]
	at AxGraves-1.14.3.jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onEnable(AxPlugin.java:112) ~[AxGraves-1.14.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:755) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:517) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:59:38] [Server thread/INFO]: [AxGraves] Disabling AxGraves v1.14.3

### Expected behaviour

I expected it to load by itself

### Steps to reproduce

Restart the server
Check console
Not enabled
Players lose items on death

### Which plugin is this issue with?

axgraves

### Versions

ax graves : [1.14.3]
Pufferfish 1.21.1

**Comment by BenceX100** [comment]
Should be fixed in 1.14.5!
