### ISSUE TITLE
[BUG] Removing last Save on MySQL

### ISSUE THREAD

**Issue by flo210500** [Artillex-Studios/Issues#23]
### Description of the bug

[23:15:51] [AxInventoryRestore-Datastore-thread/ERROR]: [com.artillexstudios.axinventoryrestore.database.impl.Base] An unexpected error occurred while removing last save for 42f5441b-ccfa-4c23-9d1d-d2d648bb9ccf!
java.sql.SQLSyntaxErrorException: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1106) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1045) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1369) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1030) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at AxInventoryRestore-3.3.2.jar/com.artillexstudios.axinventoryrestore.libs.hikari.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[AxInventoryRestore-3.3.2.jar:?]
	at AxInventoryRestore-3.3.2.jar/com.artillexstudios.axinventoryrestore.libs.hikari.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[AxInventoryRestore-3.3.2.jar:?]
	at AxInventoryRestore-3.3.2.jar/com.artillexstudios.axinventoryrestore.database.impl.Base.removeLastSaves(Base.java:632) ~[AxInventoryRestore-3.3.2.jar:?]
	at AxInventoryRestore-3.3.2.jar/com.artillexstudios.axinventoryrestore.utils.BackupLimiter.lambda$tryLimit$0(BackupLimiter.java:25) ~[AxInventoryRestore-3.3.2.jar:?]
	at AxInventoryRestore-3.3.2.jar/com.artillexstudios.axinventoryrestore.queue.PriorityThreadedQueue.run(PriorityThreadedQueue.java:62) ~[AxInventoryRestore-3.3.2.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Expected behaviour

I Expect that old Backups are been Removed

### Steps to reproduce

It comes on Every Save/Remove

### Which plugin is this issue with?

axinventoryrestore

### Versions

Current Purpur Version: 1.21.1-2324-e12a4de (MC: 1.21.1)*
AxInventory 3.3.2

MySQL:  8.0.39-0ubuntu0.20.04.1 - (Ubuntu)

**Comment by BenceX100** [comment]
This was fixed in 3.5.1.
