### ISSUE TITLE
[BUG] Not working once i add an item

### ISSUE THREAD

**Issue by IbanEtchep** [Artillex-Studios/Issues#30]
### Description of the bug

`[14:58:21] [Server thread/ERROR]: Error occurred while enabling AxAuctions v1.14.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "<local3>" is null
	at AxAuctions-1.14.0.jar/com.artillexstudios.axauctions.database.impl.Base.getCurrencyById(Base.java:234) ~[AxAuctions-1.14.0.jar:?]
	at AxAuctions-1.14.0.jar/com.artillexstudios.axauctions.database.impl.Base.load(Base.java:531) ~[AxAuctions-1.14.0.jar:?]
	at AxAuctions-1.14.0.jar/com.artillexstudios.axauctions.AxAuctions.enable(AxAuctions.java:186) ~[AxAuctions-1.14.0.jar:?]
	at AxAuctions-1.14.0.jar/com.artillexstudios.axauctions.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85) ~[AxAuctions-1.14.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`
	
	
Full logs	[https://mclo.gs/JYlkJiH](https://mclo.gs/JYlkJiH)
	
Config: https://mclo.gs/qERhlkB
Currencies: https://mclo.gs/e2MOxB8
	

### Expected behaviour

Init sould success

### Steps to reproduce

- Install 1.14.0
- Start the plugin
- Add an item
- Restart the server

### Which plugin is this issue with?

axauctions

### Versions

Pufferfish 1.21.1
AxAuctions 1.14.0

**Comment by IbanEtchep** [comment]
> This means that some currency is missing from the currencies.yml, but there are items with it in the database

No
![image](https://github.com/user-attachments/assets/eff1e48d-926e-43c2-a68e-21ddc9d7b3ef)
![image](https://github.com/user-attachments/assets/72cffba7-6d21-47ca-a211-7c334183f089)

**Comment by IbanEtchep** [comment]
![image](https://github.com/user-attachments/assets/2fc65cb3-a1f4-417b-9e52-1ab398def1bb)
Maybe it's not safe to get it by column order and and you should use resultSet.getInt("currency")

**Comment by BenceX100** [comment]
If you are looking at the right database, this really should work, I have no clue why this happens, the fifth row in the table is the right one and the currency with id 1 is indeed the Vault currency, and you have vault, so no clue why does this happen. Does this only happen with mysql? Or have you tried dropping the axauction tables (or changing the table prefix in the config)

**Comment by IbanEtchep** [comment]
I use 10.11.6-MariaDB-0+deb12u1 - Debian 12, maybe it's my db version which does not take the right order. In my old server it was working with the same configuration but a different db version :/
Could you edit your code to retrive collumns by name instead of by order? or giving me a version with debug messages to see what is going on?

**Comment by BenceX100** [comment]
Now that I have looked at the full log again, it seems like the plugin can't connect to the database
`axauctions-pool - Connection is not available, request timed out after 5000ms` - and that causes the error
Are you sure that you set the right credentials in the config?

**Comment by IbanEtchep** [comment]
Yes i have the right crédentials, if there is no item in db it loads: [https://mclo.gs/0ZcAV52](https://mclo.gs/0ZcAV52)

**Comment by BenceX100** [comment]
Not a plugin issue
