### ISSUE TITLE
[BUG] SERVER NOT STARTING

### ISSUE THREAD

**Issue by edwin1212256756** [Artillex-Studios/Issues#47]
### Description of the bug

I added the latest build to my server and the server just doesn't start at all.

error:

```
r.java:305)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:25 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:25 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:25 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:25 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:25 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:25 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:25 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:25 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:25 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:25 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:25 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:25 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:25 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:25 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:25 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:25 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:25 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:25 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:25 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:26 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:26 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:26 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:26 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:26 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:26 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:26 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:26 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:30:26 WARN]: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "permission" is null
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.selection.Region.getPlayersInZone(Region.java:37)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.zones.Zone.tick(Zone.java:52)
[15:30:26 WARN]:        at AxAFKZone-1.4.2 (1).jar//com.artillexstudios.axafkzone.schedulers.TickZones.lambda$start$1(TickZones.java:21)
[15:30:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:30:26 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:30:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:30:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Expected behaviour

server to start fine..

### Steps to reproduce

Add latest build to server.

### Which plugin is this issue with?

axafkzone

### Versions

1.4.2

**Comment by BenceX100** [comment]
Seems like one of your zones is missing this permission section: https://github.com/Artillex-Studios/AxAFKZone/blob/master/src/main/resources/zones/example-zone.yml#L18

just keep it set to "" if you want to disable it.
