### ISSUE TITLE
AxMinions not working at all

### ISSUE THREAD

**Issue by Koios39** [Artillex-Studios/Issues#51]
### Description of the bug

No minions are showing up and an error message shows up in the log.

### Expected behaviour

Minions should show up.

### Steps to reproduce

<html>
<body>

[14:03:46] [Server thread/ERROR]: Error occurred while enabling AxMinions v1.0.11 (Is it up to date?)
347 | java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.v1_21_R1.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
348 | at com.artillexstudios.axminions.libs.axapi.nms.v1_21_R1.ItemStackSerializer.deserializeFromBytes(ItemStackSerializer.java:39) ~[?:?]
349 | at com.artillexstudios.axminions.libs.axapi.nms.v1_21_R1.NMSHandler.wrapItem(NMSHandler.java:211) ~[?:?]
350 | at com.artillexstudios.axminions.libs.axapi.serializers.impl.ItemStackSerializer.deserialize(ItemStackSerializer.java:17) ~[?:?]
351 | at com.artillexstudios.axminions.libs.axapi.serializers.impl.ItemStackSerializer.deserialize(ItemStackSerializer.java:8) ~[?:?]
352 | at com.artillexstudios.axminions.data.H2DataHandler.loadMinionsForWorld(H2DataHandler.kt:140) ~[?:?]
353 | at com.artillexstudios.axminions.AxMinionsPlugin.enable(AxMinionsPlugin.kt:132) ~[?:?]
354 | at com.artillexstudios.axminions.libs.axapi.AxPlugin.onEnable(AxPlugin.java:111) ~[?:?]
355 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
356 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
357 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
358 | at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:576) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
359 | at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:490) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
360 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
361 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
362 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
363 | at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
364 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
365 | at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
366

<br class="Apple-interchange-newline">
</body>
</html>

### Which plugin is this issue with?

axminions

### Versions

Spigot version1.21.1, plugin version 1.0.12

**Comment by AverageGithub** [comment]
Update the pluin to 1.0.13, reopen if still not fixed
